2020-07-09 19:05:15 : no such table: greenhouse_AtmosphericPressure
2020-07-09 19:05:15 : no such table: greenhouse_Temperature
2020-07-09 19:05:16 : no such table: greenhouse_Humidity
2020-07-09 19:05:16 : no such table: greenhouse_SoilTemperature
2020-07-09 19:05:16 : no such table: greenhouse_SoilMoisture
2020-07-09 19:05:16 : no such table: greenhouse_Light
2020-07-09 19:05:16 : no such table: greenhouse_OutsideTemperature
2020-07-09 19:05:16 : no such table: greenhouse_HumidityOutside
2020-07-09 19:05:16 : no such table: greenhouse_ComfortIndicator
2020-07-09 19:06:23 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04345940>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:06:44 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04345448>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:07:05 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04345DC0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:07:26 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x043681D8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:07:47 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x043685F8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:08:08 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x043689E8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:08:29 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04368DD8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:08:50 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v7 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04345E38>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:09:11 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04345AF0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:19:21 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0274C0A0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:19:42 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0274C5F8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:20:03 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0274C9E8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:20:24 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0274CDD8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:20:45 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00F54208>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:21:06 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0272E9B8>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:21:27 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0274C778>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:21:48 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v7 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0274C940>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
2020-07-09 19:22:09 : HTTPConnectionPool(host='194.126.183.229', port=8080): Max retries exceeded with url: /pvliXzHfH3f2a92cQ6ACtDgVw5-_r8tW/get/v8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0274C670>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond'))
